### ISSUE TITLE
Información general

### ISSUE THREAD

**Issue by alzateg** [anfego/Laap#2]
La información general debe integrar la totalidad de la información no clínica del paciente. Creo que no debe segmentarla. O sea que en la información general debe incluir la dirección.

**Comment by anfego** [comment]
Entonces, la se debe eliminar la seccion de contacto y  direcciones, y ser remplazadas por solo una informacion general que tenga estos datos?

**Comment by alzateg** [comment]
Si. Y se deben incluir nuevos datos, como tipo de documento, en el cual se debe desplegar un menú de opciones que contengan: Cédula de ciudadanía, pasaporte, registro civil, tarjeta de identidad y cédula de extranjería. También en información general puede agregar nacionalidad, idioma, país de residencia, la edad debe aparecer inmediatamente se ponga la fecha de nacimiento y se debe actualizar automáticamente. El país, la ciudad y el departamento también debe ser con menú desplegable para evitar errores de escritura.

**Comment by anfego** [comment]
Listo, entonces partamos esto en pequenas tareas,  que puedar ser resultas y probadas independientemente. 
**1**, eliminar Contacto y Direcciones, anadir campos correspondientes en informacion general
**2**, anadir tipo de documento en un menu despeglabe. 
**3**. agrega campos de nacionalidad, ...

Y creo que este **Issue** debe ser categorizado como pregunta, y **enhancement** issues deben ser creados con cada una de estas modificiaciones
